// <auto-generated />
using System;
using Ef6CoreForPosgreSQL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Ef6CoreForPosgreSQL.Migrations
{
    [DbContext(typeof(MyWebApiContext))]
    [Migration("20230408003057_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Ef6CoreForPosgreSQL.Entities.IFarmacia", b =>
                {
                    b.Property<int>("IdFarmacia")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Direccion");

                    b.Property<bool>("Habilitado");

                    b.Property<string>("Nombre");

                    b.Property<string>("RUC");

                    b.Property<string>("RazonSocial");

                    b.Property<string>("Telefono1");

                    b.Property<string>("Telefono2");

                    b.HasKey("IdFarmacia");

                    b.ToTable("Farmacias");
                });

            modelBuilder.Entity("Ef6CoreForPosgreSQL.Entities.IFiles", b =>
                {
                    b.Property<int>("IdFile")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Estado");

                    b.Property<DateTime>("FechaSubida");

                    b.Property<int>("IdFarmacia");

                    b.Property<int>("IdPerfil");

                    b.Property<int>("IdUserScanner");

                    b.Property<string>("Nombre");

                    b.Property<string>("Type");

                    b.Property<string>("URL");

                    b.Property<string>("User");

                    b.HasKey("IdFile");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("Ef6CoreForPosgreSQL.Entities.INotificacion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NotId");

                    b.Property<string>("Uid");

                    b.HasKey("id");

                    b.ToTable("Notificacion");
                });

            modelBuilder.Entity("Ef6CoreForPosgreSQL.Entities.IPerfil", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apellido");

                    b.Property<string>("Cedula");

                    b.Property<string>("Correo");

                    b.Property<DateTime>("FechaNacimiento");

                    b.Property<bool>("Habilitado");

                    b.Property<int>("IdFarmacia");

                    b.Property<string>("Nombre");

                    b.Property<int>("Rol");

                    b.Property<string>("Telefono1");

                    b.Property<string>("Telefono2");

                    b.Property<string>("Usuario");

                    b.HasKey("id");

                    b.ToTable("Perfil");
                });

            modelBuilder.Entity("Ef6CoreForPosgreSQL.Entities.IUserScanner", b =>
                {
                    b.Property<int>("IdUserScanner")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Correo");

                    b.Property<int>("IdFarmacia");

                    b.Property<int>("IdPerfil");

                    b.Property<string>("User");

                    b.HasKey("IdUserScanner");

                    b.ToTable("UserScanners");
                });

            modelBuilder.Entity("Ef6CoreForPosgreSQL.Entities.IUsuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apellido");

                    b.Property<string>("Dni");

                    b.Property<DateTime>("FechaNacimiento");

                    b.Property<string>("Mail")
                        .IsRequired();

                    b.Property<string>("Nombre");

                    b.Property<int>("Rol");

                    b.Property<string>("Telefono1");

                    b.Property<string>("Telefono2");

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.HasKey("id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Ef6CoreForPosgreSQL.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Ef6CoreForPosgreSQL.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<int>("GroupId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Ef6CoreForPosgreSQL.Models.User", b =>
                {
                    b.HasOne("Ef6CoreForPosgreSQL.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
